[package]
name = "unfuck-gpg"
version = "0.1.0"
authors = ["seu <seu@panopticon.re>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sequoia-openpgp = "*"
